{% set name = "coveralls" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9486f353176d309066053d38edbade3aad6346c5eb8a5edde7090d3116219414

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - coveralls = coveralls.cli:main
    - python-coveralls = coveralls.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - coverage[toml] >=5.0, <7.5
    - docopt >=0.6.1, <0.7.0
    - python >=3.8
    - pyyaml >=3.10, <7.0
    - requests >=1.0.0, <3.0.0

test:
  commands:
    - coveralls --help

about:
  home: https://github.com/coveralls-clients/coveralls-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Show coverage stats online via coveralls.io
  description: |
    coveralls.io is a service for publishing your coverage stats online. This
    package provides seamless integration with coverage.py (and thus py.test,
    nosetests, etc...) in your Python projects.
  dev_url: https://github.com/coveralls-clients/coveralls-python

extra:
  recipe-maintainers:
    - thewchan
    - thekevjames
