{% set name = "coveralls" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b2a0a2bcef94f295e3cf28dcc55ca40b71c77d1c2446b538e85f0f7bc21aa69

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - coveralls = coveralls.cli:main
    - python-coveralls = coveralls.cli:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8, <3.13
  run:
    - coverage[toml] >=5.0, <8.0
    - docopt >=0.6.1, <0.7.0
    - python >=3.8, <3.13
    - pyyaml >=3.10, <7.0
    - requests >=1.0.0, <3.0.0

test:
  commands:
    - coveralls --help
    - python-coveralls --help

about:
  home: https://github.com/coveralls-clients/coveralls-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Show coverage stats online via coveralls.io
  description: |
    coveralls.io is a service for publishing your coverage stats online. This
    package provides seamless integration with coverage.py (and thus py.test,
    nosetests, etc...) in your Python projects.
  dev_url: https://github.com/coveralls-clients/coveralls-python

extra:
  recipe-maintainers:
    - thewchan
    - thekevjames
