{% set name = "coveralls" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34160385c13b0c43691ab11c080d4b10dabe3280fc0b2173c731efc5db836808

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - coveralls = coveralls.cli:main

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - coverage >=3.6
    - docopt >=0.6.1
    - python >=3.5
    - requests >=1.0.0

test:
  commands:
    - coveralls --help

about:
  home: https://github.com/coveralls-clients/coveralls-python
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Show coverage stats online via coveralls.io
  description: |
    coveralls.io is a service for publishing your coverage stats online. This
    package provides seamless integration with coverage.py (and thus py.test,
    nosetests, etc...) in your Python projects.
  dev_url: https://github.com/coveralls-clients/coveralls-python

extra:
  recipe-maintainers:
    - thewchan
    - thekevjames
