{% set name = "coveralls" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 664794748d2e5673e347ec476159a9d87f43e0d2d44950e98ed0e27b98da8346

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - coveralls = coveralls.cli:main

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools
  run:
    - coverage >=3.6
    - docopt >=0.6.1
    - python
    - pyyaml >=3.10
    - requests >=1.0.0
    - urllib3

test:
  commands:
    - coveralls --help

about:
  home: https://github.com/coveralls-clients/coveralls-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Show coverage stats online via coveralls.io
  description: |
    coveralls.io is a service for publishing your coverage stats online. This
    package provides seamless integration with coverage.py (and thus py.test,
    nosetests, etc...) in your Python projects.
  dev_url: https://github.com/coveralls-clients/coveralls-python

extra:
  recipe-maintainers:
    - goanpeca
    - thekevjames
