travis:
  secure:
    BINSTAR_TOKEN: FPuAvC+4tjKEwo+7QkzjUbk4gfxCYjXDAqQt2TRHM/zpTxjcRxfOB9Gvfm+vhR5V8y6U1jQz6h6DMes+KFjyoVe4zLdEBDcB/3O1RvRiYeDa5Mqym2rO+kXMyBlH6WbUNOpLgqFnKWK5YaS2F5FGt56DpZYlFAq20rXU7SgV14JaqdxrHP6XjUQkGf8qBAO82DnaQ4MpAJ4mtcTMfMFiv863kmLvL48y7Ah9fNGsig/4PaC1Xk0KC9FGYcFaFf4rEUIKRykKZbZUcgz4z7YfO2cJTVuD3TvWtsY2SMRom6+2ohLuA+88fJGWaPQ8VklGLf4SVFPq8KT4+403C6km/KCHzU8h2T7fpXA+9ZGPbxDFtj5OlxxWI/spgmoo+9IoOYbaMmAgCKNCi+sDl90Gq5SA5gwSOFWThY4BCUYi2r4XULc30MNQPPkQGdpGrT7on478+dPBlsc3+6iI2UuHtzA27ooxVmWY3RIQjGSrd/lD7Mid3tNuAMqKjFhyXEJgj4fbp/dZHJhb3bh6JZHDGtj3NivrrJ0OPK+L1Exlz1LAoiGbYUlDaM+U9wE7nTZNSA00rxh+yj+Xcivtu0BpLazsGX4L/T7slOqjTMPiu+tcXs7hkYZDy9dWFvz6GNe4XVs62APrH18vn/zM6xVyxnGdfbepwLFHoutY3oaiE1g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
